<a href="https://colab.research.google.com/github/eliseleahy/Pytorch-Tutorials/blob/main/00_Pytorch_Fundatmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [ ]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Introduction to Tensors

Creating tensors

Ref: https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[0]


tensor([7, 8])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,8]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0] 

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 8]])

Tensors hold matrices. So in the case above we can see that there is one 3x3 matrix in position TENSOR[0]. 

First bracket is the 1 in the torch.size

Second bracket is the 3 in the torch.size

Third bracket is the 3 in the torch.size

In [ ]:
TENSOR = torch.tensor([[[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]],
                       [[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]]])

print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([2, 2, 3, 3])
4


# Random Tensors 

Why random tensors?

Random tensors are important because the way nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnt the data. 

'start with random numbers -> look at data -> update random numbers -> look at data -> update random number'

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.4212, 0.2677, 0.4278, 0.7283],
        [0.1708, 0.4010, 0.3022, 0.2953],
        [0.8094, 0.4794, 0.1941, 0.3279]])

In [ ]:
#Create a random tensor of a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones 

In [ ]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
ones.dtype

torch.float32

# Range

create a range of tensors and tensor-like

In [ ]:
one_to_ten=torch.arange(0,10)

In [ ]:
torch.arange(0,10, 0.5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [ ]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data Type

Note- Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, #What datatype is the tensor
                               device=None, # what device is the tensor on e.g. cpu and gpu
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype can use - tensor.dtype
2. Tensors not right shape - to get shape can use - tensor.shape
3. Tensors not on the right device -  to get device can use - tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2430, 0.3240, 0.8700, 0.8322],
        [0.0537, 0.5954, 0.3015, 0.9485],
        [0.8072, 0.4994, 0.2175, 0.8677]])

In [ ]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.2430, 0.3240, 0.8700, 0.8322],
        [0.0537, 0.5954, 0.3015, 0.9485],
        [0.8072, 0.4994, 0.2175, 0.8677]])
torch.float32
torch.Size([3, 4])
cpu
