# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor

ten_1 = torch.rand(7,7)
ten_1


tensor([[0.1072, 0.6313, 0.1137, 0.4273, 0.7928, 0.9665, 0.9196],
        [0.4678, 0.3142, 0.7831, 0.4910, 0.3280, 0.2469, 0.6417],
        [0.7457, 0.0272, 0.0440, 0.3498, 0.6709, 0.1026, 0.3005],
        [0.8596, 0.6638, 0.9878, 0.4678, 0.9089, 0.6288, 0.5561],
        [0.8800, 0.5134, 0.8029, 0.0015, 0.0267, 0.6343, 0.1849],
        [0.0215, 0.0169, 0.2893, 0.2309, 0.5054, 0.6085, 0.3055],
        [0.0670, 0.1697, 0.4581, 0.4049, 0.7124, 0.4485, 0.4270]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor

ten_2 = torch.rand(1,7)
ten_2

# Perform matrix multiplication 
ten_3 = torch.matmul(ten_1, ten_2.T)

ten_3,ten_3.shape  

(tensor([[1.1980],
         [1.1059],
         [0.8433],
         [1.6545],
         [1.0931],
         [0.4168],
         [0.6900]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED=0 
torch.manual_seed(seed=RANDOM_SEED) 

# Create two random tensors
ten_4 = torch.rand(7, 7)
ten_5 = torch.rand(1,7)


# Matrix multiply tensors
ten_6=torch.matmul(ten_4,ten_5.T)
ten_6

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU

torch.cuda.seed = 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
RANDOM_SEED=1234 
torch.manual_seed(seed=RANDOM_SEED) 

# Check for access to GPU
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Create two random tensors on GPU
ten_7=torch.rand(2,3)
ten_8=torch.rand(2,3)

tensor_on_gpu_7 = ten_7.to(device)
tensor_on_gpu_8 = ten_8.to(device)
tensor_on_gpu_7, tensor_on_gpu_8 

True
cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
ten_9=torch.matmul(tensor_on_gpu_7, tensor_on_gpu_8.T)
ten_9

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
ten_9.max(),ten_9.min()
# Find min


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
ten_9.argmax(), ten_9.argmin()

# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
RANDOM_SEED=7
torch.manual_seed(seed=RANDOM_SEED) 

# Create random tensor
ten_10=torch.rand(1,1,1,10)

# Remove single dimensions
RANDOM_SEED=7
torch.manual_seed(seed=RANDOM_SEED) 
ten_11=torch.rand(10)

# Print out tensors and their shapes
print(ten_10, ten_10.shape)
print(ten_11, ten_11.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
