# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [6]:
# Import torch
import torch


# Create random tensor

ten_1 = torch.rand(7,7)
ten_1


tensor([[0.8912, 0.8815, 0.4293, 0.1201, 0.7568, 0.9779, 0.8679],
        [0.2767, 0.1628, 0.8845, 0.9019, 0.4936, 0.6304, 0.9165],
        [0.1496, 0.1905, 0.7382, 0.0777, 0.7499, 0.8064, 0.0536],
        [0.5239, 0.4671, 0.7969, 0.1323, 0.7272, 0.1298, 0.6850],
        [0.5277, 0.5166, 0.3771, 0.2513, 0.4918, 0.0057, 0.2484],
        [0.5301, 0.4442, 0.3703, 0.8233, 0.4221, 0.7553, 0.6311],
        [0.4744, 0.8542, 0.9519, 0.9999, 0.9548, 0.4424, 0.6709]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor

ten_2 = torch.rand(1,7)
ten_2

# Perform matrix multiplication 
ten_3 = torch.matmul(ten_1, ten_2.T)

ten_3,ten_3.shape  

(tensor([[2.3812],
         [2.3155],
         [1.4381],
         [1.8031],
         [1.4251],
         [2.1772],
         [3.1765]]), torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
RANDOM_SEED=0 
torch.manual_seed(seed=RANDOM_SEED) 

# Create two random tensors
ten_4 = torch.rand(7, 7)
ten_5 = torch.rand(1,7)


# Matrix multiply tensors
ten_6=torch.matmul(ten_4,ten_5.T)
ten_6

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU

torch.cuda.seed = 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
RANDOM_SEED=1234 
torch.manual_seed(seed=RANDOM_SEED) 

# Check for access to GPU
print(torch.cuda.is_available())
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Create two random tensors on GPU
ten_7=torch.rand(2,3)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
