<a href="https://colab.research.google.com/github/eliseleahy/Pytorch-Tutorials/blob/main/00_Pytorch_Fundatmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [53]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [54]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# Introduction to Tensors

Creating tensors

Ref: https://pytorch.org/docs/stable/tensors.html

In [55]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [56]:
scalar.ndim

0

In [57]:
scalar.item()

7

In [58]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [59]:
vector.shape

torch.Size([2])

In [60]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [61]:
MATRIX[0]


tensor([7, 8])

In [62]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,8]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [63]:
TENSOR.shape

torch.Size([1, 3, 3])

In [64]:
TENSOR[0] 

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 8]])

Tensors hold matrices. So in the case above we can see that there is one 3x3 matrix in position TENSOR[0]. 

First bracket is the 1 in the torch.size

Second bracket is the 3 in the torch.size

Third bracket is the 3 in the torch.size

In [65]:
TENSOR = torch.tensor([[[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]],
                       [[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]]])

print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([2, 2, 3, 3])
4


# Random Tensors 

Why random tensors?

Random tensors are important because the way nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnt the data. 

'start with random numbers -> look at data -> update random numbers -> look at data -> update random number'

In [66]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.0920, 0.9338, 0.2826, 0.9125],
        [0.2486, 0.3769, 0.9614, 0.2737],
        [0.9887, 0.7332, 0.3964, 0.0948]])

In [67]:
#Create a random tensor of a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones 

In [68]:
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [69]:
ones.dtype

torch.float32

# Range

create a range of tensors and tensor-like

In [70]:
one_to_ten=torch.arange(0,10)

In [71]:
torch.arange(0,10, 0.5)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [72]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Data Type

Note- Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device 

In [73]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None, #What datatype is the tensor
                               device=None, # what device is the tensor on e.g. cpu and gpu
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [74]:
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [76]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype can use - tensor.dtype
2. Tensors not right shape - to get shape can use - tensor.shape
3. Tensors not on the right device -  to get device can use - tensor.device

In [77]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6936, 0.0979, 0.5309, 0.9486],
        [0.9423, 0.6544, 0.0970, 0.0212],
        [0.0174, 0.1092, 0.6203, 0.7542]])

In [78]:
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.6936, 0.0979, 0.5309, 0.9486],
        [0.9423, 0.6544, 0.0970, 0.0212],
        [0.0174, 0.1092, 0.6203, 0.7542]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating Tensor Operations 

Tensor operations include: 
* Addition
* Subtraction 
* Multiplication (element-wise))
* Division 
* Matrix Multiplication 

In [79]:
#create a tensor 
tensor = torch.tensor([1,2,3])
tensor+ 10

tensor([11, 12, 13])

In [80]:
# multiply tensor by 10 
tensor*10

tensor([10, 20, 30])

In [81]:
# subtract 10 
tensor - 10

tensor([-9, -8, -7])

In [82]:
# try out PyTorch inbuilt functions 
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [83]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication need to satisfy: 
1. inner dimensions must match:
* '(3,2) @ (3,2)' - won't work 
* '(2,3) @ (3,2)' - will work
* '(3,2) @ (2,3)' - will work 

2. The resulting matrix has the shape of the out dimensions 
* '(2,3) @ (3,2)' -> (2,2)
* '(3,2) @ (2,3)' -> (3,3)

In [84]:
# Element - wise
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [85]:
# Matrix multiplication 
torch.matmul(tensor,tensor)

tensor(14)

In [86]:
# Matrix muliplication by hand 
1*1 + 2*2 + 3*3 

14

In [87]:
%%time 
value = 0 
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
value

CPU times: user 289 µs, sys: 0 ns, total: 289 µs
Wall time: 299 µs


tensor(14)

In [88]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 698 µs, sys: 0 ns, total: 698 µs
Wall time: 3.68 ms


tensor(14)

### One of the most common errors in deep learning: shape errors


In [90]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], 
                        [3,4], 
                        [5,6]])

tensor_B = torch.tensor([[7,10], 
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) ##torch.mm is the same as torch.matmul

RuntimeError: ignored

In [91]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues we can manipulate the shape of one of our tensors by taking the transpose of the matrix 

In [92]:
tensor_B.T # .T takes the transpose 

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [93]:
# The matrix multiplication mutliplication works when tensor_B is transposed 

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## finding the min, max, sum, ect... (tensor aggregation)

In [96]:
# create a tensor 
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
# find min 
torch.min(x), x.min()


(tensor(0), tensor(0))

In [98]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [103]:
#find mean - note: torch.mean function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

(tensor(45.), <function Tensor.mean>)

In [106]:
#find sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [111]:
#Find indices of the max
torch.topk(x,1)


torch.return_types.topk(
values=tensor([90]),
indices=tensor([9]))

### Finding the positional min and max

In [112]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [113]:
# Find the positional in tensor that has the minimum value 
x.argmin()

tensor(0)

In [114]:
x[0]

tensor(0)

In [115]:
x.argmax()


tensor(9)

In [116]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - rehspaes an input tensor to a defined shape
* Veiw - Returns a view of an input tensor of a certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or next to each other (hstack)
* Squeezing - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimenision to a target tensor 
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [128]:
# Create a tensor

import torch

x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [129]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [131]:
# Change the view

z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [133]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z,x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [142]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [149]:
v_stacked = torch.vstack([x,x,x,x])
v_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [150]:
# torch.squeeze() - removes all single dimensions
x_reshaped.shape

torch.Size([1, 9])

In [155]:
x_squeezed = x_reshaped.squeeze()

In [156]:
# removes the 1 dimension
x_reshaped.squeeze().shape



torch.Size([9])

In [166]:
# torch.unsqueeze() adds a single dimension to a target tensor at a dim 
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [170]:
# torch.permute rearrages the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # [height, width, colour_channels]

#permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0 

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))