<a href="https://colab.research.google.com/github/eliseleahy/Pytorch-Tutorials/blob/main/00_Pytorch_Fundatmentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook - https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [ ]:
!nvidia-smi


# Introduction to Tensors

Creating tensors

Ref: https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[0]


tensor([7, 8])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,8]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 8]]])

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR[0] 

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 8]])

Tensors hold matrices. So in the case above we can see that there is one 3x3 matrix in position TENSOR[0]. 

First bracket is the 1 in the torch.size

Second bracket is the 3 in the torch.size

Third bracket is the 3 in the torch.size

In [13]:
TENSOR = torch.tensor([[[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]],
                       [[[1,2,3], 
                         [4,5,6], 
                         [7,8,9]],
                        [[1,2,3],
                         [3,6,9],
                         [2,4,8]]]])

print(TENSOR.shape)
print(TENSOR.ndim)

torch.Size([2, 2, 3, 3])
4


# Random Tensors 

Why random tensors?

Random tensors are important because the way nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represnt the data. 

'start with random numbers -> look at data -> update random numbers -> look at data -> update random number'

In [14]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[4.1882e-02, 8.8332e-01, 6.7284e-01, 8.7642e-01],
        [5.3229e-01, 2.0101e-01, 4.3869e-05, 5.0056e-01],
        [4.4645e-01, 3.8545e-01, 8.4974e-01, 8.6630e-01]])